"""Generate the deterministic price history fixture.

Run once, commit the result. The randomness lives here, not in the product: a
committed series is reviewable in a diff, reproduces exactly in CI, and makes a
failing analysis test point at a specific number rather than at a seed.

    python scripts/generate_price_history.py

Each series is built backwards from the spot price in `quotes.json` and ends the
day BEFORE it. That gap is deliberate: the fixture provider records today's spot
as a live quote, so the newest step in the series is history-to-spot. A series
that ran up to today would instead end with a flat step - the seeded close and
the live quote being the same number - and bury the planted event one step back
where the latest-move rules cannot see it. Volatility is
per symbol, and three symbols carry a deliberately planted event so the analysis
rules have something real to find:

  * NVDA - a single-day drop large enough to clear the 'high' severity band
  * TAN  - a sustained decline, to exercise the drawdown rule
  * MSFT - deliberately quiet, so a small move there is *not* reported, which is
           the case that proves the rules discriminate rather than just fire

Weekends are skipped for equities and ETFs; crypto trades every day. The series
is daily closes, which is the granularity the rules reason about.
"""

from __future__ import annotations

import json
import random
from datetime import date, timedelta
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

FIXTURES = Path(__file__).resolve().parents[3] / "data" / "fixtures"
TRADING_DAYS = 70

#: The last day carrying a seeded close. `quotes.json`'s spot price belongs to
#: the day after, and arrives as a live quote rather than as history.
LAST_HISTORY_DAY = date(2026, 9, 14)

#: Daily volatility as a fraction, chosen to look like the instrument it names.
#: A utility-like ETF and a speculative small cap should not share a sigma, or
#: the sigma rule has nothing to distinguish.
VOLATILITY = {
    "AAPL": 0.012,
    "MSFT": 0.004,  # deliberately quiet: its moves must stay below the threshold
    "NVDA": 0.028,
    "GOOGL": 0.014,
    "SMR": 0.045,
    "CEG": 0.020,
    "VOO": 0.007,
    "QQQ": 0.010,
    "URA": 0.022,
    "TAN": 0.024,
    "BTC-USD": 0.032,
    "ETH-USD": 0.038,
    "TEVA": 0.016,
    "SAP.DE": 0.011,
}

#: symbol -> the move the live spot quote should represent against the last
#: seeded close. The series is anchored at `spot / multiplier` so that the step
#: into today's quote IS the event, rather than the event sitting in history
#: with a flat step after it.
PLANTED_EVENTS = {
    "NVDA": Decimal("0.915"),  # -8.5% into today's price: comfortably into 'high'
}

#: Symbols given a sustained downtrend, so drawdown has something to measure.
DRIFT_DOWN = {"TAN": -0.004}

CRYPTO_SUFFIXES = ("-USD",)


def is_crypto(symbol: str) -> bool:
    return symbol.endswith(CRYPTO_SUFFIXES) and symbol not in {"SAP.DE"}


def trading_days(end: date, count: int, *, include_weekends: bool) -> list[date]:
    days: list[date] = []
    cursor = end
    while len(days) < count:
        if include_weekends or cursor.weekday() < 5:
            days.append(cursor)
        cursor -= timedelta(days=1)
    return sorted(days)


def build_series(symbol: str, spot: Decimal, rng: random.Random) -> list[dict]:
    # History ends the day before the spot quote; see the module docstring.
    days = trading_days(LAST_HISTORY_DAY, TRADING_DAYS, include_weekends=is_crypto(symbol))
    anchor = spot / PLANTED_EVENTS[symbol] if symbol in PLANTED_EVENTS else spot
    sigma = VOLATILITY.get(symbol, 0.015)
    drift = DRIFT_DOWN.get(symbol, 0.0)

    # Walk backwards from the known spot price so the last close matches it.
    closes: list[Decimal] = [anchor]
    for _ in range(len(days) - 1):
        step = rng.gauss(0.0, sigma) + drift
        previous = closes[-1] / Decimal(1 + step)
        closes.append(previous)
    closes.reverse()

    return [
        {"date": day.isoformat(), "close": str(close.quantize(Decimal("0.01"), ROUND_HALF_UP))}
        for day, close in zip(days, closes, strict=True)
    ]


def main() -> int:
    quotes = json.loads((FIXTURES / "quotes.json").read_text())
    rng = random.Random(20260915)  # fixed seed: the output is committed, not regenerated in CI

    series = {
        symbol: build_series(symbol, Decimal(str(entry["price"])), rng)
        for symbol, entry in sorted(quotes["prices"].items())
    }

    output = {
        "_comment": (
            "Synthetic daily closes for the demo portfolio, generated by "
            "scripts/generate_price_history.py with a fixed seed. The series ends the day "
            "before the spot price in quotes.json, so the newest move is history-to-spot. "
            "Plausible but invented: NVDA's last close sits 8.5% above its spot price so the "
            "live quote reads as a sharp drop, TAN carries a sustained decline, and MSFT is "
            "deliberately quiet. Do not read anything into these numbers."
        ),
        "history_ends": "2026-09-14",
        "spot_belongs_to": "2026-09-15",
        "series": series,
    }
    path = FIXTURES / "price-history.json"
    path.write_text(json.dumps(output, indent=2) + "\n")
    print(f"wrote {path} ({len(series)} symbols, {TRADING_DAYS} closes each)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
