"""Write the committed exchange calendar from NYSE's rules (decision D25).

    python scripts/generate_exchange_calendar.py [--first-year Y] [--last-year Y]
                                                 [--out DIR] [--check]

Writes `data/calendar/xnys.json`: every full closure and 13:00 early close for
the years asked, from `app/core/nyse_holiday_rules.py`. **Entries marked
`"source": "manual"` are kept** - the closures no rule predicts (a national day
of mourning) are typed into the file by hand and survive every regeneration.

Without year arguments the file's own range is kept, so the yearly chore is one
command: `--last-year` one higher, then commit the diff. The test
`test_calendar_covers_the_next_90_days` says when it is due.

`--check` writes nothing and exits 1 when the committed file is not what the
rules would write (a hand edit to a rule-made day, or a rule changed without
regenerating). CI runs the same comparison as a test.

An operator's tool, offline and quick; it is not part of any run.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path

from app.config import get_settings
from app.core import nyse_holiday_rules as rules
from app.core.exchange_calendar import CALENDAR_FILE, XNYS
from app.core.market_sessions import US

EARLY_CLOSE = "13:00"
DESCRIPTION = (
    "NYSE and Nasdaq full closures and 13:00 early closes (New York time). Generated by "
    "services/ai/scripts/generate_exchange_calendar.py from app/core/nyse_holiday_rules.py; "
    'entries with "source": "manual" are added by hand and kept on regeneration.'
)


def _clock(minute: int) -> str:
    return f"{minute // 60:02d}:{minute % 60:02d}"


def _entries(days: list[rules.CalendarDay]) -> list[dict[str, str]]:
    return [{"date": entry.day.isoformat(), "name": entry.name, "source": "rule"} for entry in days]


def build(first_year: int, last_year: int, previous: dict | None) -> dict:
    """The calendar document for the years, keeping `previous`'s manual entries."""
    if first_year > last_year:
        raise ValueError(f"first year {first_year} is after last year {last_year}")
    years = range(first_year, last_year + 1)
    closures = [row for year in years for row in _entries(rules.closures(year))]
    early = [row for year in years for row in _entries(rules.early_closes(year))]
    for key, rows in (("closures", closures), ("early_closes", early)):
        for row in (previous or {}).get(key, []):
            if row.get("source") == "manual" and first_year <= int(row["date"][:4]) <= last_year:
                rows.append(row)
        rows.sort(key=lambda row: row["date"])
    return {
        "calendar": XNYS,
        "description": DESCRIPTION,
        "timezone": US.timezone,
        "open": _clock(US.open_minute),
        "close": _clock(US.close_minute),
        "early_close": EARLY_CLOSE,
        "first_year": first_year,
        "last_year": last_year,
        "closures": closures,
        "early_closes": early,
    }


def render(document: dict) -> str:
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--first-year", type=int)
    parser.add_argument("--last-year", type=int)
    parser.add_argument("--out", type=Path, default=Path(get_settings().calendar_dir))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    path = args.out / CALENDAR_FILE
    previous = json.loads(path.read_text(encoding="utf-8")) if path.exists() else None
    this_year = datetime.now(UTC).year
    first = args.first_year or (previous["first_year"] if previous else this_year - 1)
    last = args.last_year or (previous["last_year"] if previous else this_year + 4)
    text = render(build(first, last, previous))

    if args.check:
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != text:
            print(f"{path} is not what the rules write; run without --check", file=sys.stderr)
            return 1
        print(f"{path} is in step with the rules ({first}-{last})")
        return 0
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"wrote {path} ({first}-{last})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
