"""Build docs/DECISIONS.md, the index of architecture decisions, from .claude/MEMORY.md.

    python3 scripts/build_decision_index.py          # rewrite the index
    python3 scripts/build_decision_index.py --check  # exit 1 if it is out of date

The decisions themselves - each with the alternative it rejected and the failure
it prevents - are written once, in the "Decisions that were argued, not obvious"
section of .claude/MEMORY.md. This index is generated from their numbers and
titles, so it cannot drift from them; services/ai/tests/test_decision_index.py
runs `--check` in CI. Standard library only, so it runs with any python3.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MEMORY = REPO_ROOT / ".claude" / "MEMORY.md"
INDEX = REPO_ROOT / "docs" / "DECISIONS.md"
SECTION = "## Decisions that were argued, not obvious"

HEADER = """# Decision index

Every decision that was argued rather than obvious, in the order it was made. The full text of
each - what was chosen, what was rejected, and the failure it prevents - is in the "Decisions
that were argued, not obvious" section of [.claude/MEMORY.md](../.claude/MEMORY.md), under the
same number. The founding choices (framework, RPC, stores, scheduling ownership, money) are the
table in [DESIGN.md section 2](DESIGN.md#2-decisions-and-what-was-rejected).

Generated by `python3 scripts/build_decision_index.py` - edit MEMORY.md, then run it; CI fails
while this file is out of date.

| # | Decision |
|---|---|
"""


def decisions(memory: str) -> list[tuple[int, str]]:
    section = memory.split(SECTION, 1)[1].split("\n## ", 1)[0]
    found = re.findall(r"^(\d+)\. \*\*(.+?)\*\*", section, re.MULTILINE | re.DOTALL)
    return [
        (int(number), " ".join(title.split()).rstrip(".")) for number, title in found
    ]


def escape_pipes(text: str) -> str:
    return text.replace("|", "\\|")


def render(items: list[tuple[int, str]]) -> str:
    # Escaped outside the f-string: python3 before 3.12 rejects a backslash inside one.
    rows = "".join(f"| {number} | {escape_pipes(title)} |\n" for number, title in items)
    return HEADER + rows


def main() -> int:
    items = decisions(MEMORY.read_text(encoding="utf-8"))
    numbers = [number for number, _ in items]
    if numbers != list(range(1, len(numbers) + 1)):
        print(
            f"decision numbers are not 1..{len(numbers)} in order: {numbers}",
            file=sys.stderr,
        )
        return 1
    expected = render(items)
    if "--check" in sys.argv[1:]:
        current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
        if current != expected:
            print(
                "docs/DECISIONS.md is out of date: run python3 scripts/build_decision_index.py",
                file=sys.stderr,
            )
            return 1
        return 0
    INDEX.write_text(expected, encoding="utf-8")
    print(f"wrote {INDEX.relative_to(REPO_ROOT)} ({len(items)} decisions)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
